Spring.aplication.name=customer;


server.port=8081

spring.datasource.url=jdbc:postgresql://ep-silent-hat-a8a8ao50-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SVchMZ0g1ePy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=validate
sping.flyway.baseline-on-migrate=true

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

#Cofniguración Bucket de Cloudinary
cloudinary.cloud-name=dlyd4vt9z
cloudinary.api-key=797963227595552
cloudinary.api-secret=XSZA366Co_y4PeGow6-0lKZR9ZM

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration