global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'digitalbank-aws-produccion'
    metrics_path: '/actuator/prometheus'
    scheme: https  # Muy importante porque AWS usa HTTPS
    static_configs:
      - targets: ['mpdpzt7cyw.us-east-1.awsapprunner.com'] # Solo el dominio, sin https:// ni rutas